package rs.raf.bank_service.domain.enums;

public enum TransactionType {
    CONFIRM_PAYMENT,
    CONFIRM_TRANSFER,
    APPROVE_LOAN,
    PAY_INSTALLMENT,
    CREATE_PAYMENT,
    CREATE_TRANSFER,
    REJECT_PAYMENT,

    RESERVE_BALANCE,
    FREE_BALANCE,
    UPDATE_BALANCE,
    SYSTEM_PAYMENT,
    DELAY_EXTERNAL_PAYMENT,
    PROCESS_EXTERNAL_PAYMENT,

}
